# Form implementation generated from reading ui file 'src/blobbackup/ui/backupstarteddialog.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BackupStartedDialog(object):
    def setupUi(self, BackupStartedDialog):
        BackupStartedDialog.setObjectName("BackupStartedDialog")
        BackupStartedDialog.resize(500, 350)
        BackupStartedDialog.setMinimumSize(QtCore.QSize(500, 350))
        self.verticalLayout = QtWidgets.QVBoxLayout(BackupStartedDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_label = QtWidgets.QLabel(BackupStartedDialog)
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout.addWidget(self.logo_label)
        self.label_2 = QtWidgets.QLabel(BackupStartedDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.check_label = QtWidgets.QLabel(BackupStartedDialog)
        self.check_label.setText("")
        self.check_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.check_label.setObjectName("check_label")
        self.verticalLayout.addWidget(self.check_label)
        self.label_3 = QtWidgets.QLabel(BackupStartedDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(BackupStartedDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(BackupStartedDialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.close_button = QtWidgets.QPushButton(BackupStartedDialog)
        self.close_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(BackupStartedDialog)
        QtCore.QMetaObject.connectSlotsByName(BackupStartedDialog)

    def retranslateUi(self, BackupStartedDialog):
        _translate = QtCore.QCoreApplication.translate
        BackupStartedDialog.setWindowTitle(_translate("BackupStartedDialog", "Backup Started - Blobbackup"))
        self.label_2.setText(_translate("BackupStartedDialog", "Blobbackup"))
        self.label_3.setText(_translate("BackupStartedDialog", "Backup Started!"))
        self.label_4.setText(_translate("BackupStartedDialog", "Blobbackup is now backing up your computer in the background."))
        self.label.setText(_translate("BackupStartedDialog", "You can safely close this window."))
        self.close_button.setText(_translate("BackupStartedDialog", "Close"))
