# Form implementation generated from reading ui file 'src/blobbackup/ui/changepassworddialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChangePasswordDialog(object):
    def setupUi(self, ChangePasswordDialog):
        ChangePasswordDialog.setObjectName("ChangePasswordDialog")
        ChangePasswordDialog.resize(300, 250)
        ChangePasswordDialog.setMinimumSize(QtCore.QSize(300, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(ChangePasswordDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.heading_label = QtWidgets.QLabel(ChangePasswordDialog)
        self.heading_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.heading_label.setObjectName("heading_label")
        self.verticalLayout.addWidget(self.heading_label)
        self.email_line_edit = QtWidgets.QLineEdit(ChangePasswordDialog)
        self.email_line_edit.setObjectName("email_line_edit")
        self.verticalLayout.addWidget(self.email_line_edit)
        self.password_line_edit = QtWidgets.QLineEdit(ChangePasswordDialog)
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_line_edit.setObjectName("password_line_edit")
        self.verticalLayout.addWidget(self.password_line_edit)
        self.new_password_line_edit = QtWidgets.QLineEdit(ChangePasswordDialog)
        self.new_password_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.new_password_line_edit.setObjectName("new_password_line_edit")
        self.verticalLayout.addWidget(self.new_password_line_edit)
        self.confirm_new_password_line_edit = QtWidgets.QLineEdit(ChangePasswordDialog)
        self.confirm_new_password_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirm_new_password_line_edit.setObjectName("confirm_new_password_line_edit")
        self.verticalLayout.addWidget(self.confirm_new_password_line_edit)
        self.change_password_button = QtWidgets.QPushButton(ChangePasswordDialog)
        self.change_password_button.setObjectName("change_password_button")
        self.verticalLayout.addWidget(self.change_password_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(ChangePasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(ChangePasswordDialog)

    def retranslateUi(self, ChangePasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        ChangePasswordDialog.setWindowTitle(_translate("ChangePasswordDialog", "Change Password - Blobbackup"))
        self.heading_label.setText(_translate("ChangePasswordDialog", "Change Your Password"))
        self.email_line_edit.setPlaceholderText(_translate("ChangePasswordDialog", "Email"))
        self.password_line_edit.setPlaceholderText(_translate("ChangePasswordDialog", "Password"))
        self.new_password_line_edit.setPlaceholderText(_translate("ChangePasswordDialog", "New Password"))
        self.confirm_new_password_line_edit.setPlaceholderText(_translate("ChangePasswordDialog", "Confirm New Password"))
        self.change_password_button.setText(_translate("ChangePasswordDialog", "Change Password"))
