# Form implementation generated from reading ui file 'src/blobbackup/ui/developerdialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeveloperDialog(object):
    def setupUi(self, DeveloperDialog):
        DeveloperDialog.setObjectName("DeveloperDialog")
        DeveloperDialog.resize(400, 400)
        DeveloperDialog.setMinimumSize(QtCore.QSize(400, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(DeveloperDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(DeveloperDialog)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.unlock_button = QtWidgets.QPushButton(DeveloperDialog)
        self.unlock_button.setObjectName("unlock_button")
        self.horizontalLayout.addWidget(self.unlock_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(DeveloperDialog)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prune_button = QtWidgets.QPushButton(DeveloperDialog)
        self.prune_button.setObjectName("prune_button")
        self.horizontalLayout_2.addWidget(self.prune_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(DeveloperDialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(DeveloperDialog)
        QtCore.QMetaObject.connectSlotsByName(DeveloperDialog)

    def retranslateUi(self, DeveloperDialog):
        _translate = QtCore.QCoreApplication.translate
        DeveloperDialog.setWindowTitle(_translate("DeveloperDialog", "Developer - Blobbackup"))
        self.label_2.setText(_translate("DeveloperDialog", "The \"unlock\" command removes stale locks that have been created by other Blobbackup processes."))
        self.unlock_button.setText(_translate("DeveloperDialog", "Unlock"))
        self.label_3.setText(_translate("DeveloperDialog", "The \"prune\" command checks the repository and removes data that is not referenced and therefore not needed any more."))
        self.prune_button.setText(_translate("DeveloperDialog", "Prune"))
        self.label.setText(_translate("DeveloperDialog", "Note: These are very advanced operations. You will only need to use them in special circumstances."))
