# Form implementation generated from reading ui file 'src/blobbackup/ui/requestfulldiskdialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RequestFullDiskDialog(object):
    def setupUi(self, RequestFullDiskDialog):
        RequestFullDiskDialog.setObjectName("RequestFullDiskDialog")
        RequestFullDiskDialog.resize(500, 400)
        RequestFullDiskDialog.setMinimumSize(QtCore.QSize(500, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(RequestFullDiskDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(RequestFullDiskDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.guide_label = QtWidgets.QLabel(RequestFullDiskDialog)
        self.guide_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.guide_label.setObjectName("guide_label")
        self.verticalLayout.addWidget(self.guide_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.screenshot_label = QtWidgets.QLabel(RequestFullDiskDialog)
        self.screenshot_label.setText("")
        self.screenshot_label.setObjectName("screenshot_label")
        self.horizontalLayout.addWidget(self.screenshot_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.open_button = QtWidgets.QPushButton(RequestFullDiskDialog)
        self.open_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.open_button.setObjectName("open_button")
        self.horizontalLayout_2.addWidget(self.open_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.skip_button = QtWidgets.QLabel(RequestFullDiskDialog)
        self.skip_button.setObjectName("skip_button")
        self.horizontalLayout_3.addWidget(self.skip_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(RequestFullDiskDialog)
        QtCore.QMetaObject.connectSlotsByName(RequestFullDiskDialog)

    def retranslateUi(self, RequestFullDiskDialog):
        _translate = QtCore.QCoreApplication.translate
        RequestFullDiskDialog.setWindowTitle(_translate("RequestFullDiskDialog", "Full Disk Access - Blobbackup"))
        self.label_3.setText(_translate("RequestFullDiskDialog", "Blobbackup requires \"Full Disk Access\" to work properly."))
        self.guide_label.setText(_translate("RequestFullDiskDialog", "Please grant it from System Preferences and restart the app (<a href=\"https://blobbackup.com\" style=\"color: blue; text-decoration: underline\">Guide</a>)."))
        self.open_button.setText(_translate("RequestFullDiskDialog", "Open System Preferences"))
        self.skip_button.setText(_translate("RequestFullDiskDialog", "<html><head/><body><p><a href=\"#\"><span style=\" text-decoration: underline; color:#0068da;\">I\'m just restoring</span></a></p></body></html>"))
