# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/blobbackup/ui/restoredialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RestoreDialog(object):
    def setupUi(self, RestoreDialog):
        RestoreDialog.setObjectName("RestoreDialog")
        RestoreDialog.resize(500, 350)
        RestoreDialog.setMinimumSize(QtCore.QSize(500, 350))
        self.verticalLayout = QtWidgets.QVBoxLayout(RestoreDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.snapshots_combo_box = QtWidgets.QComboBox(RestoreDialog)
        self.snapshots_combo_box.setObjectName("snapshots_combo_box")
        self.verticalLayout.addWidget(self.snapshots_combo_box)
        self.snapshot_tree_layout = QtWidgets.QVBoxLayout()
        self.snapshot_tree_layout.setObjectName("snapshot_tree_layout")
        self.verticalLayout.addLayout(self.snapshot_tree_layout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.restore_button = QtWidgets.QPushButton(RestoreDialog)
        self.restore_button.setObjectName("restore_button")
        self.horizontalLayout.addWidget(self.restore_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(RestoreDialog)
        QtCore.QMetaObject.connectSlotsByName(RestoreDialog)

    def retranslateUi(self, RestoreDialog):
        _translate = QtCore.QCoreApplication.translate
        RestoreDialog.setWindowTitle(_translate("RestoreDialog", "Restore Files - Blobbackup"))
        self.restore_button.setText(_translate("RestoreDialog", "Restore To"))
