name: Tests

on:
  pull_request:
    branches: [ dev, test ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Backends test
      run: |
        python -m blobbackup.local_backend_test
    - name: Repo test
      run: |
        python -m blobbackup.repo2_test
    
