name: Tests

on:
  pull_request:
    branches: [ dev, test ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd src && python chunker_setup.py build_ext --inplace
    - name: Backends test
      run: |
        cd src && python local_backend_test.py --verbose
    - name: Repo test
      run: |
        cd src && python repo2_test.py --verbose
    
