name: Build binaries

on:
  push:
    branches: [ master, build, dev]
  pull_request:
    branches: [ master, build, dev]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 16
      matrix:
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install macos dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install create-dmg
    - name: Build and upload executable (macos)
      if: matrix.os == 'macos-latest'
      run: |
        make build_osx
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'macos-latest'
      with:
        name: BlobBackup_osx_v1.0.1.dmg
        path: BlobBackup.dmg